import type { NextPage } from "next";
import Head from "next/head";
import styles from "./blogs.module.scss";

export const Blogs: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>Blogs</main>

			<footer className={styles.footer}></footer>
		</div>
	);
};
